referenceless_regression_metric:
  class_path: comet.models.ReferencelessRegression
  init_args:
    nr_frozen_epochs: 0.2
    keep_embeddings_frozen: False
    optimizer: AdamW
    encoder_learning_rate: 1.0e-05
    final_activation: Sigmoid
    learning_rate: 3.1e-05
    layerwise_decay: 0.95
    encoder_model: BERT
    pretrained_model: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2  
    pool: avg
    layer: mix
    dropout: 0.15
    batch_size: 4
    train_data: /fs/startiger0/nmoghe/data/qe_data/wmt-metrics/wmt20/2020-da-mlqe-raw-train.csv
    validation_data: /fs/startiger0/nmoghe/data/qe_data/wmt-metrics/wmt20/2020-mlqe-raw-dev.csv
    hidden_sizes:
      - 2048
      - 1024
    
trainer: ../trainer.yaml
early_stopping: ../early_stopping_mse.yaml
model_checkpoint: ../model_checkpoint_mse.yaml
